### ISSUE TITLE
Terraform not exited gracefully with ctrl-c

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/furyctl#386] opened 2023-05-30 13:53 UTC
While running Furyctl in a terraform step, terraform is not exited gracefully and in one test with @lzecca78 we had duplicated resources (VPC) on AWS

We are using the preview version 0.25.0-alpha1

**Comment by Al-Pragliola** [comment] 2023-05-30 14:26
Closing because a duplicate of #291

**Closed by Al-Pragliola** 2023-05-30 14:26 UTC
Labels: duplicate
